services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker
      POSTGRES_DB: trackerdb
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trackerdb
      SPRING_DATASOURCE_USERNAME: tracker
      SPRING_DATASOURCE_PASSWORD: tracker
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules

volumes:
  frontend_node_modules:
